#!perl

BEGIN {
  unless ($ENV{RELEASE_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for release candidate testing');
  }
}

# This file was automatically generated by Dist::Zilla::Plugin::PodSyntaxTests.
use Test::More;
eval { require Test::Pod; Test::Pod->VERSION(1.41); Test::Pod->import(); };
plan(skip_all => "Test::Pod not installed: $@; skipping") if $@;

all_pod_files_ok();
